### PR TITLE
CRUD Material

### PR DESCRIPTION
**Pull request by isaqueha**
This PR adds the CRUD for Construction Materials.

Link: https://trello.com/c/PWIVX8ka

⚠️ **WARNING** ⚠️ 
Please merge this after [this PR #4](https://github.com/dev-3-2019-1/SGRA-Backend/pull/4)

### CODE REVIEW

**Review by nathanss — CHANGES_REQUESTED** [review]
I think the Materials CRUD should only have name, description and unit of measure. 

The rest (project, consumption and responsible) should be created at a different screen, as it is a N..N relationship with the material. 

What you think?

**Comment by isaqueha** [comment]
@nathanss, looking now I believe that this makes sense.
We should have a different screen for the N..N association between Materials and Projects.
Also, do you think that this is the same in the `requirements` CRUD?
Maybe we have a N..N relationship there as well: https://trello.com/c/Whn29vDL/22-us-3-crud-requisitos-legais

I will change this in the next days.

**Comment by nathanss** [comment]
@isaqueha Yes, I think legal requirements are the same scenario. Maybe a new screen just for this association should exist.

**Comment by isaqueha** [comment]
@nathanss, I've created a new screen for the N..N association between Materials and Projects.
Please go http://localhost:3000/projectMaterials. 
You can also go inside a Project/Material/User to see its associations.

Can you please review it?

**Review by nathanss — APPROVED** [review]

**Pull request merged**
